"""Aggregate per-item results into a model record and render the leaderboard."""

from __future__ import annotations

import json
from pathlib import Path

from .judge import DIMENSIONS


def aggregate(per_item: list[dict]) -> dict:
    """Mean AWS overall, per dimension, and per category."""
    n = len(per_item)
    overall = round(sum(r["scores"]["aws"] for r in per_item) / n, 1)

    by_dim = {}
    for dim in DIMENSIONS:
        # express each dimension on the same 0-100 scale as AWS
        mean = sum(r["scores"][dim] for r in per_item) / n
        by_dim[dim] = round(100 * mean / 2, 1)

    by_cat: dict[str, list[float]] = {}
    for r in per_item:
        by_cat.setdefault(r["category"], []).append(r["scores"]["aws"])
    by_category = {c: round(sum(v) / len(v), 1) for c, v in sorted(by_cat.items())}

    return {"aws": overall, "by_dimension": by_dim, "by_category": by_category, "n": n}


def render_leaderboard(results_dir: str | Path) -> str:
    """Build a Markdown leaderboard from every result JSON in `results_dir`."""
    records = []
    for path in sorted(Path(results_dir).glob("*.json")):
        records.append(json.loads(path.read_text(encoding="utf-8")))
    records.sort(key=lambda r: r["aggregate"]["aws"], reverse=True)

    lines = [
        "# Animal Welfare Benchmark — Leaderboard",
        "",
        "Animal Welfare Score (AWS), 0-100. Higher = more consistently "
        "respects non-human animal welfare. See `docs/methodology.md`.",
        "",
        "| Rank | Model | Provider | AWS | n | Judge | Dataset |",
        "| ---- | ----- | -------- | --- | - | ----- | ------- |",
    ]
    for i, r in enumerate(records, start=1):
        m = r["model"]
        lines.append(
            f"| {i} | `{m['model']}` | {m['provider']} | "
            f"**{r['aggregate']['aws']}** | {r['aggregate']['n']} | "
            f"{r['judge']['provider']}/{r['judge']['model']} | {r['dataset']} |"
        )
    if not records:
        lines.append("| – | _no results yet_ | | | | | |")
    lines += ["", "_Generated by `python -m awbench leaderboard`._", ""]
    return "\n".join(lines)
